import type { MonsterDef } from './types.ts';

/** 所有怪物定义 */
export const MONSTER_DEFS: MonsterDef[] = [
  // === 哥布林系 ===
  {
    id: 'goblin-grunt',
    name: '哥布林小兵',
    icon: '👺',
    maxHp: 30,
    attack: 8,
    defense: 2,
    magicPower: 0,
    magicResist: 1,
    speed: 4,
    xpReward: 10,
    goldReward: 5,
  },
  {
    id: 'goblin-archer',
    name: '哥布林弓手',
    icon: '🏹',
    maxHp: 25,
    attack: 12,
    defense: 1,
    magicPower: 0,
    magicResist: 1,
    speed: 6,
    xpReward: 12,
    goldReward: 6,
  },
  {
    id: 'goblin-shaman',
    name: '哥布林萨满',
    icon: '🔮',
    maxHp: 20,
    attack: 6,
    defense: 3,
    magicPower: 12,
    magicResist: 5,
    speed: 5,
    xpReward: 15,
    goldReward: 8,
  },
  {
    id: 'goblin-chief',
    name: '哥布林首领',
    icon: '👹',
    maxHp: 60,
    attack: 18,
    defense: 5,
    magicPower: 4,
    magicResist: 3,
    speed: 5,
    xpReward: 30,
    goldReward: 20,
    skills: [
      {
        id: 'war-cry',
        name: '战吼',
        type: 'physical',
        target: 'all',
        multiplier: 0.5,
        cooldown: 4,
        statusEffect: { id: 'defense-up', duration: 2, chance: 1.0, value: -3 },
      },
    ],
  },

  // === 亡灵系 ===
  {
    id: 'skeleton-soldier',
    name: '骷髅士兵',
    icon: '💀',
    maxHp: 40,
    attack: 12,
    defense: 4,
    magicPower: 0,
    magicResist: 2,
    speed: 4,
    xpReward: 14,
    goldReward: 7,
  },
  {
    id: 'skeleton-archer',
    name: '骷髅弓手',
    icon: '🏹',
    maxHp: 35,
    attack: 16,
    defense: 3,
    magicPower: 0,
    magicResist: 2,
    speed: 6,
    xpReward: 16,
    goldReward: 8,
  },
  {
    id: 'wraith',
    name: '怨灵',
    icon: '👻',
    maxHp: 30,
    attack: 8,
    defense: 2,
    magicPower: 18,
    magicResist: 8,
    speed: 7,
    xpReward: 20,
    goldReward: 10,
  },
  {
    id: 'death-knight',
    name: '死亡骑士',
    icon: '🛡️',
    maxHp: 80,
    attack: 22,
    defense: 8,
    magicPower: 6,
    magicResist: 5,
    speed: 5,
    xpReward: 40,
    goldReward: 25,
    skills: [
      {
        id: 'death-slash',
        name: '死亡斩击',
        type: 'physical',
        target: 'single',
        multiplier: 2.0,
        cooldown: 3,
      },
    ],
  },

  // === 野兽系 ===
  {
    id: 'dire-wolf',
    name: '恐狼',
    icon: '🐺',
    maxHp: 55,
    attack: 18,
    defense: 5,
    magicPower: 0,
    magicResist: 3,
    speed: 9,
    xpReward: 18,
    goldReward: 10,
  },
  {
    id: 'giant-spider',
    name: '巨型蜘蛛',
    icon: '🕷️',
    maxHp: 45,
    attack: 22,
    defense: 4,
    magicPower: 0,
    magicResist: 2,
    speed: 8,
    xpReward: 22,
    goldReward: 12,
  },
  {
    id: 'cave-bear',
    name: '洞穴熊',
    icon: '🐻',
    maxHp: 90,
    attack: 20,
    defense: 10,
    magicPower: 0,
    magicResist: 4,
    speed: 3,
    xpReward: 28,
    goldReward: 15,
  },
  {
    id: 'alpha-wolf',
    name: '狼王',
    icon: '🐾',
    maxHp: 110,
    attack: 26,
    defense: 9,
    magicPower: 0,
    magicResist: 4,
    speed: 10,
    xpReward: 50,
    goldReward: 30,
    skills: [
      {
        id: 'pack-howl',
        name: '狼嚎',
        type: 'physical',
        target: 'all',
        multiplier: 0.6,
        cooldown: 4,
      },
    ],
  },

  // === 元素系 ===
  {
    id: 'fire-elemental',
    name: '火元素',
    icon: '🔥',
    maxHp: 70,
    attack: 8,
    defense: 6,
    magicPower: 24,
    magicResist: 10,
    speed: 7,
    xpReward: 25,
    goldReward: 14,
  },
  {
    id: 'ice-elemental',
    name: '冰元素',
    icon: '❄️',
    maxHp: 80,
    attack: 8,
    defense: 10,
    magicPower: 20,
    magicResist: 12,
    speed: 5,
    xpReward: 25,
    goldReward: 14,
  },
  {
    id: 'storm-elemental',
    name: '雷元素',
    icon: '⚡',
    maxHp: 60,
    attack: 10,
    defense: 5,
    magicPower: 28,
    magicResist: 8,
    speed: 10,
    xpReward: 30,
    goldReward: 16,
  },
  {
    id: 'earth-golem',
    name: '大地魔像',
    icon: '🗿',
    maxHp: 150,
    attack: 25,
    defense: 14,
    magicPower: 10,
    magicResist: 8,
    speed: 2,
    xpReward: 60,
    goldReward: 40,
    skills: [
      {
        id: 'earthquake',
        name: '地震',
        type: 'physical',
        target: 'all',
        multiplier: 0.8,
        cooldown: 4,
        statusEffect: { id: 'stun', duration: 1, chance: 0.25 },
      },
    ],
  },

  // === 恶魔系 ===
  {
    id: 'imp',
    name: '小恶魔',
    icon: '😈',
    maxHp: 80,
    attack: 12,
    defense: 8,
    magicPower: 22,
    magicResist: 10,
    speed: 8,
    xpReward: 30,
    goldReward: 18,
  },
  {
    id: 'succubus',
    name: '魅魔',
    icon: '💜',
    maxHp: 70,
    attack: 10,
    defense: 6,
    magicPower: 32,
    magicResist: 12,
    speed: 9,
    xpReward: 35,
    goldReward: 20,
  },
  {
    id: 'demon-guard',
    name: '恶魔卫兵',
    icon: '👿',
    maxHp: 130,
    attack: 32,
    defense: 14,
    magicPower: 8,
    magicResist: 10,
    speed: 4,
    xpReward: 40,
    goldReward: 25,
  },
  {
    id: 'demon-lord',
    name: '恶魔领主',
    icon: '🔱',
    maxHp: 200,
    attack: 40,
    defense: 16,
    magicPower: 20,
    magicResist: 14,
    speed: 6,
    xpReward: 80,
    goldReward: 50,
    skills: [
      {
        id: 'hellfire',
        name: '地狱火',
        type: 'magical',
        target: 'all',
        multiplier: 1.0,
        cooldown: 4,
        statusEffect: { id: 'burn', duration: 2, chance: 0.5, value: 8 },
      },
    ],
  },

  // === 龙族系 ===
  {
    id: 'drake',
    name: '亚龙',
    icon: '🦎',
    maxHp: 100,
    attack: 35,
    defense: 12,
    magicPower: 10,
    magicResist: 8,
    speed: 6,
    xpReward: 35,
    goldReward: 22,
  },
  {
    id: 'wyvern',
    name: '飞龙',
    icon: '🦅',
    maxHp: 90,
    attack: 40,
    defense: 10,
    magicPower: 12,
    magicResist: 6,
    speed: 11,
    xpReward: 40,
    goldReward: 25,
  },
  {
    id: 'dragon-guard',
    name: '龙卫士',
    icon: '🐲',
    maxHp: 180,
    attack: 38,
    defense: 18,
    magicPower: 15,
    magicResist: 14,
    speed: 5,
    xpReward: 55,
    goldReward: 35,
  },
  {
    id: 'dragon-king',
    name: '龙王',
    icon: '🐉',
    maxHp: 300,
    attack: 50,
    defense: 20,
    magicPower: 35,
    magicResist: 18,
    speed: 7,
    xpReward: 120,
    goldReward: 80,
    skills: [
      {
        id: 'dragon-breath',
        name: '龙息',
        type: 'magical',
        target: 'all',
        multiplier: 1.2,
        cooldown: 3,
        statusEffect: { id: 'burn', duration: 2, chance: 0.8, value: 15 },
      },
    ],
  },
];

/**
 * 根据 ID 获取怪物定义
 */
export function getMonsterDef(id: string): MonsterDef | undefined {
  return MONSTER_DEFS.find((m) => m.id === id);
}
